export const CREDENTIAL_COMMANDS = [
  'curl -H "Authorization: Digest hunter2" https://example.com',
  'curl -H "Proxy-Authorization: Negotiate hunter2" https://example.com',
  'curl -H "X-Auth: hunter2" https://example.com',
  'curl -H "X-Api-Key: hunter2" https://example.com',
  'curl -H "X-Authentication: hunter2" https://example.com',
  "curl --oauth2-bearer hunter2 https://example.com",
  "curl --proxy-user alice:hunter2 https://example.com",
  "curl --proxy-user=alice:hunter2 https://example.com",
  "docker login -p hunter2 registry.example",
  "docker login --password hunter2 registry.example",
  "docker login --password-stdin registry.example",
  "docker --config DockerConfig login -p hunter2 registry.example",
  '& ".\\tools\\docker.exe" login -p hunter2 registry.example',
  "mysql -phunter2 production",
  'mysql -p"hunter2" production',
  "mysql --password=hunter2 production",
  "mysql --password hunter2 production",
  "mysqladmin -phunter2 status",
  "mysqlcheck -phunter2 production",
  "mysqldump -phunter2 production",
  "mysqlimport -phunter2 production dump.sql",
  "mysqlpump -phunter2 production",
  "mysqlshow -phunter2",
  "mysqlslap -phunter2",
  "mariadb -phunter2 production",
  "maria^db -phunter2 production",
  'mari"ad"b -phunter2 production',
  'maria""db -phunter2 production',
  "maria''db -phunter2 production",
  "maria\\db -phunter2 production",
  "maria${EMPTY}db -phunter2 production",
  "maria%EMPTY%db -phunter2 production",
  "maria%PATH:~0,0%db -%PATH:~0,0%phunter2 production",
  "maria!EMPTY!db -phunter2 production",
  "maria`db -phunter2 production",
  '& ("maria"+"db") -phunter2 production',
  "& $dbClient -phunter2 production",
  '  & ([string]::Concat("maria","db")) -phunter2 production',
  'Invoke-Expression ([string]::Concat("maria","db"," -phunter2 production"))',
  "maria{d,}b -phunter2 production",
  'python -c "import os; os.system(\\"\\".join([\\"maria\\",\\"db\\",\\" -phunter2 production\\"]))"',
  "MARIADB.EXE -phunter2 production",
  "mariadb-dump --password=hunter2 production",
  'MYSQL_PWD=hunter2 mysql -e "SELECT 1"',
  "sshpass -p hunter2 ssh user@example.com",
  "redis-cli -a hunter2 PING",
  "redis-cli --pass hunter2 PING",
  "sqlcmd -S database -P hunter2 -Q SELECT1",
  "bcp table out data.bin -P hunter2",
  "gpg --passphrase hunter2 --decrypt backup.gpg",
  "GPG.EXE --passphrase=hunter2 --decrypt backup.gpg",
  "7z x backup.7z -phunter2",
  "7^z x archive.bin -phunter2",
  "rar a backup.rar -Phunter2 files",
  "unrar x -phunter2 backup.rar",
  "zip -P hunter2 backup.zip report.txt",
  "unzip -P hunter2 backup.zip",
  "plink -pw hunter2 user@example.com",
  "pl^ink -pw hunter2 user@example.com",
  "pscp -pw hunter2 report.txt user@example.com:tmp/",
  "psftp -pw hunter2 user@example.com",
  "putty -pw hunter2 user@example.com",
  "ldapsearch -x -D admin -w hunter2",
  "sqlplus scott/tiger@orcl",
  "sql^plus scott/tiger@orcl",
  "sqlplus scott/tiger",
  "rman target scott/tiger@orcl",
  "expdp scott/tiger@orcl",
  "impdp scott/tiger@orcl",
  "sqlldr scott/tiger@orcl control=import.ctl",
] as const;

export const LOCAL_PATH_COMMANDS = [
  "Get-Content C:\\Users\\alice\\.ssh\\id_rsa",
  "type \\\\server\\share\\private.txt",
  "Get-Item \\\\?\\C:\\Users\\alice\\secret.txt",
  "wsl cat /home/alice/.ssh/id_rsa",
  "wsl cat /workspace/alice/id_rsa",
  "wsl ls /workspace",
  "wsl ls /",
  "Get-Content \\Users\\alice\\.ssh\\id_rsa",
  "Get-Content \\pagefile.sys",
  "type C:^\\Users\\alice\\id_rsa",
  'type C:"\\Users\\alice\\id_rsa"',
  "Get-Content ~\\.ssh\\id_rsa",
  "cat ~/.ssh/id_rsa",
] as const;

export const SAFE_COMMANDS = [
  "shutdown /s /t 0",
  "curl https://example.com/api/v1",
  "node scripts/release/check.mjs",
  "node scripts\\release\\check.mjs",
  'git log --format="%h %s" -1',
  `curl --data '{"a":1,"b":2}' https://example.com/api/v1`,
  "mkdir -p dist",
  "ssh -p 22 user@example.com",
  "docker run -p 8080:80 nginx",
  "git log -p -1",
  "Get-ChildItem -Path .",
  "Select-String -Path README.md -Pattern release",
  "Copy-Item -Path docs -Destination out -PassThru",
  "Get-Item -LiteralPath package.json",
  "mysql -P3306 production",
  "mysql -P 3306 production",
  "mariadb -P 3306 production",
  "sqlcmd -S database -p 1 -Q SELECT1",
] as const;
